apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  targetNamespace: kubevirt
  releaseName: kubevirt
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: kubevirt
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: istio
      namespace: bigbang
