---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 5m
  path: "./kustomizations/kubevirt"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-cd-pkg
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: kubevirt
      name: kubevirt
  timeout: 5m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
