apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.13.7
  secretRef:
    name: private-git-server