apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  targetNamespace: metallb
  releaseName: metallb
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./charts/metallb
      sourceRef:
        kind: GitRepository
        name: metallb
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  # dependsOn:
  #   - name: istio
  #     namespace: bigbang
